apiVersion: v1
kind: Service
metadata:
  generateName: "gs-{{gameType | lower}}-"
  labels:
    app.kubernetes.io/managed-by: "nautikal"
    nautikal.io/game-server-id: "{{gameServerId}}"
spec:
  selector:
    nautikal.io/game-server-id: "{{gameServerId}}"
  type: LoadBalancer
  ports:
    {%- for port in ports %}
    - port: {{port}}
      targetPort: {{port}}
    {%- endfor %}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  generateName: "gs-{{gameType | lower}}-"
  labels:
    app.kubernetes.io/managed-by: "nautikal"
    nautikal.io/game-server-id: "{{gameServerId}}"
spec:
  accessModes:
    - ReadWriteOnce
  {%- if storageClassName %}
  storageClassName: "{{storageClassName}}"
  {%- endif %}
  resources:
    requests:
      storage: "{{storage}}"
