apiVersion: v1
kind: Service
metadata:
  generateName: "gs-{{gameType | lower}}-"
  labels:
    app.kubernetes.io/managed-by: "nautikal"
    nautikal.io/game-server-id: "{{gameServerId}}"
spec:
  selector:
    nautikal.io/game-server-id: "{{gameServerId}}"
  type: LoadBalancer
  ports:
    - port: 22
      targetPort: 22
      protocol: "TCP"
      name: sftp
    {%- for servicePort in ports %}
    {%- if servicePort.protocol == 'Both' %}
    - port: {{servicePort.port}}
      targetPort: {{servicePort.port}}
      protocol: "TCP"
      name: "{{servicePort.port}}-tcp"
    - port: {{servicePort.port}}
      targetPort: {{servicePort.port}}
      name: "{{servicePort.port}}-udp"
      protocol: "UDP"
    {%- else %}
    - port: {{servicePort.port}}
      targetPort: {{servicePort.port}}
      protocol: "{{servicePort.protocol}}"
    {%- endif %}
    {%- endfor %}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  generateName: "gs-{{gameType | lower}}-"
  labels:
    app.kubernetes.io/managed-by: "nautikal"
    nautikal.io/game-server-id: "{{gameServerId}}"
spec:
  accessModes:
    - ReadWriteOnce
  {%- if storageClassName %}
  storageClassName: "{{storageClassName}}"
  {%- endif %}
  resources:
    requests:
      storage: "{{storage}}"
